## Ustreamer base Service
x-ustreamer-svc: &ustreamer-svc
  image: mkuf/ustreamer:latest
  restart: unless-stopped
  command: --host=0.0.0.0 --port=8080 --slowdown --device=/dev/webcam --brightness=128 --resolution=1920x1080 --format=MJPEG --desired-fps=30

## Add your personal config here
services:
  klipper:
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
      #- /dev/serial/by-id/usb-Klipper_rp2040_E6614C311B0E5B35-if00:/dev/serial/by-id/usb-Klipper_rp2040_E6614C311B0E5B35-if00

  webcam:
    <<: *ustreamer-svc
    devices:
      - /dev/v4l/by-id/usb-046d_HD_Pro_Webcam_C920_81EC5CEF-video-index0:/dev/webcam
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.webcam.loadbalancer.server.port=8080"
      - "traefik.http.routers.webcam.rule=PathPrefix(`/webcam`)"
      - "traefik.http.routers.webcam.entrypoints=web"
      - "traefik.http.middlewares.webcam.stripprefix.prefixes=/webcam"
      - "traefik.http.routers.webcam.middlewares=webcam"